# Site setings
name: 'Travels with Kevan'
description: 'Kaitlyn + Eugene + Van = KEVan'
meta_description: 'Vanlife travel duo in a self-converted Promaster campervan'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'twk.jpg'
  greetings: "!!!!UNDER CONSTRUCTION!!!!  Hello! We are Kaitlyn and Eugene, and we are traveling in our self-converted Promaster named Kevan."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://travelswithkevan.com/
disqus: 'travelswithkevan'
#mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
#ga_analytics: 

# Contact form setings
email: travelswithkevan+websitecontact@gmail.com
formspree_endpoint: xbjpvbjj
contact_page_description: "Hello, you can use the below form to send us a message with any questions you may have. It is also good to reach out to us via Instagram for faster responses."
thankyou_page_description: "Your message has been successfully sent!"

# Social links
#twitter: 'justgoodthemes'
#facebook: 'username'
#github: 'justgoodthemes'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
instagram: 'TravelsWithKevan'
#pinterest: 'username'
#linkedin: 'username'
#producthunt: '@username'
#quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Van Build
    url: /van-build
  - text: Contact Us
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

