# Site setings
name: 'Travels With Kevan'
description: 'Kaitlyn + Eugene + Van = KEVan'
meta_description: 'Vanlife travel duo in a self-converted Promaster campervan'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'twk.svg'
  greetings: "Hello! We are Kaitlyn and Eugene, and we are traveling in our self-converted Promaster named Kevan."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://travelswithkevan.com/
disqus: 'travelswithkevan'
#mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
#ga_analytics: 

# Contact form setings
email: travelswithkevan@gmail.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent!"

# Social links
#twitter: 'justgoodthemes'
#facebook: 'username'
#github: 'justgoodthemes'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
instagram: 'TravelsWithKevan'
#pinterest: 'username'
#linkedin: 'username'
#producthunt: '@username'
#quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
